# Generated by Django 5.0.6 on 2024-06-02 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker_app', '0002_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='text',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses_tracker_app.category')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
