# Generated by Django 5.0.6 on 2024-06-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker_app', '0003_alter_category_text_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
