# Generated by Django 5.0.6 on 2024-06-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses_tracker_app', '0005_category_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='topic',
            new_name='category',
        ),
    ]
